# Generated by Django 3.0.2 on 2020-03-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField()),
                ('use_bitly', models.BooleanField(default=False)),
                ('short_url', models.URLField()),
            ],
        ),
    ]
