# Generated by Django 2.2.6 on 2019-11-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
