# Generated by Django 3.0.2 on 2020-03-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='clicks_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=32),
        ),
    ]
