# Generated by Django 3.0.2 on 2020-03-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_project', '0002_auto_20200318_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='use_bitly',
            field=models.BooleanField(),
        ),
    ]
