# Generated by Django 2.2.6 on 2019-11-21 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('second_project', '0002_auto_20191119_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reviewer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
