# Generated by Django 2.2.6 on 2019-11-29 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_project', '0003_book_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
