# Generated by Django 3.0.2 on 2020-03-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_project', '0004_auto_20200319_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='url_hash',
            field=models.CharField(default=0, max_length=32),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.URLField(),
        ),
    ]
