# Generated by Django 2.2.6 on 2019-12-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_project', '0006_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.TextField(max_length=450),
        ),
    ]
