# Generated by Django 3.0.5 on 2020-04-15 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=128)),
                ('review', models.CharField(max_length=450)),
                ('rating', models.IntegerField(default=0, max_length=10)),
                ('likenumber', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('likedone', models.ManyToManyField(related_name='users_likes', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
