# Generated by Django 3.0.5 on 2020-04-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamereview',
            name='rating',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
