# Generated by Django 3.0.5 on 2020-04-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0002_auto_20200415_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamereview',
            name='rating',
            field=models.FloatField(default=0, max_length=10, null=True),
        ),
    ]
