# Generated by Django 3.0.5 on 2020-04-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0003_auto_20200417_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamereview',
            old_name='game_title',
            new_name='title',
        ),
    ]
