# Generated by Django 3.0.5 on 2020-04-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0004_auto_20200417_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamereview',
            name='game_url',
            field=models.URLField(null=True),
        ),
    ]
