# Generated by Django 3.0.5 on 2020-04-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0005_gamereview_game_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamereview',
            name='show_in_feed',
            field=models.BooleanField(default=False),
        ),
    ]
