# Generated by Django 2.2.6 on 2019-11-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_project', '0002_auto_20191115_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='No name', max_length=15),
        ),
    ]
